service: aws-sfn-handson

frameworkVersion: '2'

plugins:
  - serverless-step-functions
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1


functions:
  hello:
    handler: handler.hello
  add:
    handler: handler.add
  double:
    handler: handler.double
  square:
    handler: handler.square
  bigSquare:
    handler: handler.bigSquare
  finalize:
    handler: handler.finalize
  fetchUsers:
    handler: handler.fetchUsers
  fetchTodos:
    handler: handler.fetchTodos
  apiGatewayTrigger:
    handler: handler.apiGatewayTrigger
  s3FileUploadTrigger:
    handler: handler.s3FileUploadTrigger

stepFunctions:
  stateMachines:
    hello:
      name: hello
      definition:
        Comment: The great hello world
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: 
              Fn::GetAtt: [hello,Arn]
            End: true
    method-chaining-math:
      name: method-chaining-math
      definition:
        Comment: Example to demonstrate function chaining using SFN
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource:
              Fn::GetAtt: [add,Arn]
            Next: Double
          Double:
            Type: Task
            Resource:
              Fn::GetAtt: [double,Arn]
            Next: IsBigNumber
          IsBigNumber:
            Type: Choice
            Choices: 
              - Variable: $
                NumericGreaterThan: 50
                Next: BigSquare
            Default: Square
          Square:
            Type: Task
            Resource:
              Fn::GetAtt: [square,Arn]
            End: true
            Retry:
              - ErrorEquals: [NumberIsTooBig]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [NumberIsTooBig]
                Next: NumberIsTooBigDefaultResponse
          BigSquare:
            Type: Task
            Resource:
              Fn::GetAtt: [bigSquare,Arn]
            End: true
          NumberIsTooBigDefaultResponse:
            Type: Pass
            Result: -1
            End: True
    parallel-poc:
      name: parallel-poc
      definition:
        Comment: A Hello World example of the Amazon States Language using Pass states
        StartAt: InitializeInParallel
        States:
          InitializeInParallel:
            Type: Parallel
            Branches:
            - StartAt: Add
              States:
                Add:
                  Type: Task
                  Resource: 
                    Fn::GetAtt: [add,Arn]
                  Next: Double
                Double:
                  Type: Task
                  Resource: 
                    Fn::GetAtt: [double,Arn]
                  Next: Square
                Square:
                  Type: Task
                  Resource: 
                    Fn::GetAtt: [square,Arn]
                  End: true
            - StartAt: NestedParallel
              States:
                NestedParallel:
                  Type: Parallel
                  Branches:
                  - StartAt: FetchUser
                    States:
                      FetchUser:
                        Type: Task
                        Resource: 
                          Fn::GetAtt: [fetchUsers,Arn]
                        End: true
                  - StartAt: FetchTodo
                    States:
                      FetchTodo:
                        Type: Task
                        Resource: 
                          Fn::GetAtt: [fetchTodos,Arn]
                        End: true
                  End: true
            - StartAt: Wait5Seconds
              States:
                Wait5Seconds:
                  Type: Wait
                  Seconds: 5
                  End: true
            Next: ThenFinalize
          ThenFinalize:
            Type: Task
            Resource: 
              Fn::GetAtt: [finalize,Arn]
            End: true
    all-about-pass:
      name: all-about-pass
      definition:
        StartAt: ParallelPath
        States:
          ParallelPath: 
            Type: Parallel 
            Branches:
              - StartAt: AddZ
                States:
                  AddZ:
                    Type: Pass
                    Result: 42
                    ResultPath: $.z
                    End: true
              - StartAt: OverrideX
                States:
                  OverrideX:
                    Type: Pass
                    Result: 42
                    ResultPath: $.x
                    End: true
            Next: FinalizePath
          FinalizePath:
            Type: Pass
            InputPath: $[0]
            End: True
    map-simple:
      name: map-simple
      definition:
        StartAt: "SimpleMap"
        States:
          SimpleMap:
            Type: Map
            End: true
            # MaxConcurrency: 1
            Iterator:
              StartAt: DynamicWait
              States:
                DynamicWait:
                  Type: Wait
                  SecondsPath: $.delay
                  Next: PassWait
                PassWait:
                  Type: Pass
                  InputPath: $.delay
                  End: True 
    map-advanced:
      name: map-advanced
      definition:
        StartAt: "AdvancedMap"
        States:
          AdvancedMap:
            Type: Map
            End: true
            # MaxConcurrency: 1
            ItemsPath: $.inputs
            Parameters:
              delay.$ : $$.Map.Item.Value
              executionId.$: $$.Execution.Id
              groupId.$: $.groupdId
            Iterator:
              StartAt: DynamicWait
              States:
                DynamicWait:
                  Type: Wait
                  SecondsPath: $.delay
                  End : true
    api-gateway-trigger:
      name: api-gateway-trigger
      events:
        - http:
            path: /agw-sfn
            method: POST
      definition: 
        StartAt: ApiGateway
        States:
          ApiGateway:
            Type: Task
            Resource:
              Fn::GetAtt: [apiGatewayTrigger, Arn]
            End: true
    s3-file-upload-trigger:
      name: s3-file-upload-trigger
      events:
        - cloudwatchEvent:
            event:
              source:
                - aws.s3
              detail-type:
                - AWS API Call via CloudTrail # This is abolsutely important!!! We can not change it, it's under type!
              detail:
                eventSource:
                  - s3.amazonaws.com
                eventName:
                  - PutObject
                requestParameters:
                  bucketName: 
                    - ts-dev-ass-practice-bucket
      definition: 
        StartAt: TransformEvent
        States:
          TransformEvent:
            Type: Pass
            Parameters: 
              eventName.$ : $.detail.eventName
              resources.$: $.detail.resources
            ResultPath: $
            Next: S3PutObjectTrigger
          S3PutObjectTrigger:
            Type: Task
            Resource:
              Fn::GetAtt: [s3FileUploadTrigger, Arn]
            End: true
    human-interaction-using-activity:
      name: human-interaction-using-activity
      definition:
        StartAt: CheckoutCode
        States:
          CheckoutCode:
            Type: Pass
            Result: Code checkout complete!
            Next: BuildCode
          BuildCode:
            Type: Pass
            Result: Code build complete!
            Next: WaitForApproval
          WaitForApproval:
            Type: Task
            Resource: arn:aws:states:${aws:region}:${aws:accountId}:activity:po-approval
            Next: Deploy
          Deploy:
            Type: Pass
            Result: Deployment complete!
            End: True
    sns-interaction:
      name: sns-interaction
      definition:
        StartAt: SNSPublishDynamic
        States:
          SNSPublishDynamic:
            Type: Task
            Resource: arn:aws:states:::sns:publish # VVI - special resource by SFN service for SNS
            Parameters:
              Message.$: $.message
              TopicArn.$: $.snsTopic
              MessageAttributes:
                mamaMia:
                  DataType: String
                  StringValue.$: $.attributes.mamaMia
            End: true
    sqs-integration:
      name: sqs-integration
      definition:
        StartAt: SQSPublishDynamic
        States: 
          SQSPublishDynamic:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage # VVI - special resource by SFN service for SQS
            Parameters:
              MessageBody.$: $.messageBody
              QueueUrl.$: $.queueUrl
              MessageAttributes:
                mamaMia:
                  DataType: String
                  StringValue.$: $.attributes.mamaMia
            End: true
  activities:
    - po-approval
                
